Netflix/metaflow-service

- .github/workflows/dockerimage.yml
- Dockerfile
- Dockerfile.metadata_service
- Dockerfile.migration_service
- README.md
- docker-compose.yml
- metadata_service/api/__init__.py
- metadata_service/api/admin.py
- metadata_service/api/artifact.py
- metadata_service/api/metadata.py
- metadata_service/api/run.py
- metadata_service/api/step.py
- metadata_service/api/task.py
- metadata_service/api/utils.py
- metadata_service/data/db_utils.py
- metadata_service/data/models.py
- metadata_service/data/postgres_async_db.py
- migration_service/api/__init__.py
- migration_service/api/admin.py
- migration_service/api/utils.py
- migration_service/data/postgres_async_db.py
- migration_service/get_virtual_env.py
- migration_service/migration_files/1_create_tables.sql
- migration_service/migration_files/20200603104139_add_str_id_cols.sql
- migration_service/migration_server.py
- migration_service/requirements.txt
- migration_service/run_script.py
- migration_tools.py
- setup.py
Migration Service
a tool to help users manage underlying DB migrations and launch
the most recent compatible version of the metadata service
Metadata Service changes
bump version to 2.0.0
add support for user provided run_ids and task_ids
add heartbeat column to be used in the future
> Migration Tool and user provided ids

- metadata_service/data/models.py
Fix bug in setting of create timestamp for task and metadata objects
> only set ts if missing for task and metadata

- migration_service/api/utils.py
- migration_service/data/postgres_async_db.py
Bug Fixes for Migration service:
- Correct issue where db_schema_status
- Escape apostrophes in params for postgres connection
> escape apostrophe in postgres params and fix status endpoint

- .github/workflows/test.yml
- setup.cfg
* adds PEP8 codestyle checks. Serves as a reporting tool for now instead of failing the pipeline due to style errors, as there are errors raised by the current codebase.
consider changing to a hard-fail on style errors once codebase has been unified.
> Add Codestyle check to repository workflow 

- services/ui_backend_service/README-websocket.md
- services/ui_backend_service/README.md
- services/ui_backend_service/api/utils.py
- services/ui_backend_service/api/ws.py
- services/ui_backend_service/tests/integration_tests/notify_test.py
- services/ui_backend_service/tests/integration_tests/utils.py
- services/ui_backend_service/tests/integration_tests/ws_test.py
Introduces ability to deliver past Websocket events while subscribing to resources (defined by `since` parameter):
```json
{
"type": "SUBSCRIBE", 
"resource": "path-to-subscribable-restful-resource",
"uuid": "client-generated-uuid",
"since": 1602752197
}
```
This event queue TTL is 5 minutes by default and can be controlled with `WS_QUEUE_TTL_SECONDS` environment variable. This TTL is used by the UI as well to determine if client data is stale in case reconnecting took too long (and prompts user to refresh browser if that's the case).
Added 3 integration tests:
- `ws_test.test_subscription_queue` - Make sure past data is returned correctly when `since` parameter is provided
- `ws_test.test_subscription_queue_without_since` - Make sure past data is not returned in case `since` parameter …
> Websocket past data: `since` to return missing data

- services/data/models.py
- services/data/postgres_async_db.py
- services/ui_backend_service/api/data_refiner.py
- services/ui_backend_service/api/notify.py
- services/ui_backend_service/api/task.py
- services/ui_backend_service/api/utils.py
- services/ui_backend_service/cache/search_artifacts_action.py
- services/ui_backend_service/cache/utils.py
- services/ui_backend_service/tests/integration_tests/notify_test.py
- services/ui_backend_service/tests/integration_tests/tasks_test.py
* Add generic postprocessing to enrich database responses with content from S3.
* change find_records postprocessing helper to accept async callbacks
* adds `task_ok` s3 location to Task database responses, that gets postprocessed to the actual content.
> Add artifact refinement for database responses

- services/ui_backend_service/api/log.py
- services/ui_backend_service/tests/integration_tests/log_test.py
- services/ui_backend_service/tests/integration_tests/metadata_test.py
Add backward compatibility support for S3 log path construction where past runs only supported log metadata for the first attempt.
This PR also adds integration tests for https://github.com/Netflix/metaflow-service/pull/30
> S3 log assume path

- services/data/postgres_async_db.py
- services/ui_backend_service/tests/integration_tests/runs_test.py
- services/ui_backend_service/tests/integration_tests/utils.py
* Adds a 2-week cutoff for old runs with no heartbeat data. Older than 2 weeks get marked as failed, newer still count as running.
* Added integration tests for new (heartbeat) statuses and old statuses, including cutoff period.
> Add failed status cutoff period for old runs without heartbeat.

- services/data/postgres_async_db.py
- services/ui_backend_service/api/heartbeat_monitor.py
- services/ui_backend_service/api/notify.py
- services/ui_backend_service/tests/integration_tests/tasks_test.py
- services/ui_backend_service/tests/integration_tests/utils.py
- services/ui_backend_service/ui_server.py
- refactors heartbeat monitor into an abstract for shared functionality, also documenting the common interface
- adds Task heartbeat monitor. Accounts for attempt_id when expiring task heartbeats.
- add test coverage for tasks with heartbeat
> Add task heartbeat monitor

- services/ui_backend_service/cache/get_artifacts_action.py
- services/ui_backend_service/cache/search_artifacts_action.py
- services/ui_backend_service/cache/store.py
* Fix to the way result keys are generated from cache actions. Makes a copy of existing_keys, as the cache server expects all keys to be produced that were promised by the response from `format_request` (can not omit existing keys)
* added error handling to run parameters event handler in case the params fetch raises an error (no-op on the websocket broadcast in this case)
> Include existing keys in generated result key set of cache actions

- docker-compose.development.yml
- services/ui_backend_service/README.md
- services/ui_backend_service/cache/store.py
This PR introduces new environment variable `PREFETCH_RUNS_SINCE` how many past seconds is considered when fetching most recent runs.
Current default values:
- `PREFETCH_RUNS_SINCE` in seconds, defaults to 2 days ago (86400 * 2 seconds)
- `PREFETCH_RUNS_LIMIT` defaults to 50
Default values for local development (`docker-compose.development.yml`):
- `PREFETCH_RUNS_SINCE` 3600
- `PREFETCH_RUNS_LIMIT` 1
> Prefetch default rules: past 2 days and maximum of 50 runs.

- docker-compose.development.yml
- services/ui_backend_service/api/ws.py
- services/ui_backend_service/cache/s3op.py
- services/ui_backend_service/cache/store.py
- services/ui_backend_service/requirements.txt
Following changes were introduced:
- `cache/s3op.py` - `NUM_WORKERS_DEFAULT = 2`
- `cache/store.py` - `CacheAsyncClient(max_actions=16)` (artifact+dag)
- `api/ws.py` - postprocess concurrency limit to `8`
Following environment variables were introduced:
- `S3_NUM_WORKERS` - defaults to `2`
- `CACHE_ARTIFACT_MAX_ACTIONS` - defaults to `16`
- `CACHE_DAG_MAX_ACTIONS` - defaults to `16`
- `WS_POSTPROCESS_CONCURRENCY_LIMIT` - defaults to `8`
Adds one dependency `throttler==1.2.0` for adjusting postprocess concurrency limit.
> UI: Adjust cache and postprocessing concurrent limits

- services/ui_backend_service/api/dag.py
- services/ui_backend_service/cache/generate_dag_action.py
- services/ui_backend_service/cache/get_artifacts_action.py
- services/ui_backend_service/cache/store.py
- services/ui_backend_service/ui_server.py
- services/utils/__init__.py
* passes traces on exceptions from the cache action subprocesses to api responses correctly.
* adds signal and exception handlers for main event loop for logging purposes.
* adds logging to common exception catches, including error 500 responses from api.
Log level can be controlled by the `LOGLEVEL` environment variable. Defaults to a very verbose `INFO` level.
> Enhance logging support and api responses for subprocess traces

- services/ui_backend_service/cache/store.py
* fixes regression from moving event emitters to ExecutorEventEmitter. Added a wrapper for the run parameters event handler
> fix run parameters event handler not being awaited

- services/ui_backend_service/api/heartbeat_monitor.py
* Fixes find_records queries in heartbeat monitor to always use run_number internally
> Fix heartbeat monitor using run_id as run_number 

- services/ui_backend_service/api/heartbeat_monitor.py
- services/ui_backend_service/api/notify.py
- services/ui_backend_service/api/ws.py
- services/ui_backend_service/cache/store.py
- services/ui_backend_service/tests/integration_tests/notify_test.py
- services/ui_backend_service/tests/integration_tests/utils.py
- services/ui_backend_service/ui_server.py
* Revert event emitter back to AsyncIOEventEmitter due to better performance, and this not being the root cause in the end for deadlocks.
> Revert earlier event emitter changes back to AsyncIOEventEmitter

- Dockerfile.ui_service
- services/ui_backend_service/api/admin.py
- services/utils/__init__.py
* Adds build args to ui_service dockerfile and exposes them as env variables BUILD_COMMIT_HASH and BUILD_TIMESTAMP
* exposes the aforementioned values as part of the ui_service `/version` api response.
> Add ui backend git commit hash and build date

- services/data/postgres_async_db.py
* Adds missing run_number to task query joins. This has a big impact on performance due to the tables only having a unique index from primary keys.
> Add missing run_number to task query joins

- services/ui_backend_service/api/heartbeat_monitor.py
* Opting to spawn tasks instead of awaiting inside the heartbeat check iteration to make sure the loop is not blocked by slow broadcasts.
> Fix to possibly blocking heartbeat monitor check loop

- services/ui_backend_service/api/heartbeat_monitor.py
- services/ui_backend_service/api/notify.py
- services/ui_backend_service/api/ws.py
- Remove postprocessing when adding task to heartbeat monitor
- notify.py process queue with `create_task` instead of `await`
- notify.py: don't pass table instance (with connection pool) to ws, instead use table_name and use ws connection pool
> UI performance optimization

- services/ui_backend_service/README.md
- services/ui_backend_service/ui_server.py
Use path prefix in case UI service is served under non-root path (`example.com/api/`):
- `PATH_PREFIX=/api` [defaults to None]
> UI service: support non-root paths using `PATH_PREFIX`

- services/ui_backend_service/api/notify.py
`pg_notify` task is sometimes terminated unexpectedly for unknown reason by the event loop. This sometimes happened instantly after server start, sometimes took several days to occure.
It seems that asyncio Queue `get_nowait()` fixes the issue, however I'm not completely sure why.
`get()` - https://github.com/python/cpython/blob/master/Lib/asyncio/queues.py#L150
`get_nowait()` - https://github.com/python/cpython/blob/master/Lib/asyncio/queues.py#L176
> Fix pg_notify listener terminated unexpectedly

- services/ui_backend_service/api/admin.py
- services/ui_backend_service/tests/integration_tests/__init__.py
- services/ui_backend_service/tests/integration_tests/admin_test.py
- services/ui_backend_service/tests/integration_tests/utils.py
* configure assertion helpers for resources correctly.
* fix version test for admin route
* add test for default admin links. Assert response content type for admin links route
* set admin links once during server init, instead of reading file on every request
> Integration test fixes

- services/data/models.py
- services/data/postgres_async_db.py
- services/ui_backend_service/README.md
- services/ui_backend_service/api/run.py
- services/ui_backend_service/api/utils.py
- services/ui_backend_service/tests/integration_tests/runs_test.py
Introduce `real_user` column for runs that displays user's name or `NULL` in case of non-users (user -tag missing).
Non-users will be ordered last while grouping.
> Run: real_user column for non-users

- services/data/postgres_async_db.py
- services/ui_backend_service/tests/integration_tests/runs_test.py
Added subquery to get maximum attempt_id for runs thus preventing duplicate records.
> Fix: Runs list duplicate in case of end step is retried

- services/data/postgres_async_db.py
- increases heartbeat timestamp threshold for queries, so runs/tasks do not get marked as failed because of lag between client-server communications
> change heartbeat_ts threshold for queries to include a buffer

- services/data/postgres_async_db.py
- services/ui_backend_service/tests/integration_tests/status_attempts_test.py
- services/ui_backend_service/tests/integration_tests/status_runs_test.py
- services/ui_backend_service/tests/integration_tests/status_tasks_test.py
- services/ui_backend_service/tests/integration_tests/tasks_test.py
Added more integration tests for attempt/task/run statuses.
Task `finished_at` field is now populated with:
```sql
COALESCE(attempt_ok.ts_epoch, done.ts_epoch, task_ok.ts_epoch, attempt.ts_epoch) AS finished_at
```
Integration tests now include ability to mock S3 postprocessing behaviour.
> Status integration tests

- services/data/postgres_async_db.py
- services/ui_backend_service/api/dag.py
- services/ui_backend_service/api/heartbeat_monitor.py
- services/ui_backend_service/api/log.py
- services/ui_backend_service/api/utils.py
- services/ui_backend_service/api/ws.py
- services/ui_backend_service/data/cache/store.py
- add support for benchmarking sql queries through api requests with `benchmark=true` param.
- runs `EXPLAIN ANALYZE` and logs the output when benchmark flag is set
> Add sql query benchmarking support

- services/data/postgres_async_db.py
```
ValueError: too many values to unpack (expected 2)
ERROR:aiohttp.server:Error handling request
Traceback (most recent call last):
File "/usr/local/lib/python3.7/site-packages/aiohttp/web_protocol.py", line 418, in start
resp = await task
File "/usr/local/lib/python3.7/site-packages/aiohttp/web_app.py", line 458, in _handle
resp = await handler(request)
File "/root/services/utils/__init__.py", line 93, in wrapper
return web.Response(status=db_response.response_code,
AttributeError: 'Response' object has no attribute 'response_code'
```
> Fix 'ValueError: too many values to unpack' from postgres_async_db.py

- services/data/postgres_async_db.py
- services/ui_backend_service/api/utils.py
- services/ui_backend_service/tests/unit_tests/utils_test.py
Use quotation marks to prevent conflicts with PostgreSQL reserved keywords.
Example:
```sql
SELECT * FROM (VALUES('foo')) T (user); -- Failure
SELECT * FROM (VALUES('foo')) T ("user"); -- Success
```
> Use quotation marks for column names to prevent error with reserved keywords

- services/data/postgres_async_db.py
- services/ui_backend_service/README.md
Adds two environment variables for heartbeat check configuration
- `HEARTBEAT_THRESHOLD` - controls at what point a heartbeat is considered expired. Default is `WAIT_TIME * 6`
- `OLD_RUN_FAILURE_CUTOFF_TIME` - for runs that do not have a heartbeat, controls at what point a `running` status run should be considered failed. Default is 2 weeks
> Make heartbeat interval configurable for UI heartbeat checks

- services/data/postgres_async_db.py
- services/ui_backend_service/tests/integration_tests/runs_test.py
Reverts Netflix/metaflow-service#105
It seems that tags are important for Meson based runs.
> Revert "SFN user considered NULL"

- .github/workflows/test.yml
- services/data/postgres_async_db.py
- services/migration_service/data/postgres_async_db.py
- services/ui_backend_service/tests/integration_tests/utils.py
- services/utils/__init__.py
PostgreSQL connection kept timing out (after 60s x3) and the integration job appeared "stuck" due to timeout+retry loop.
For some reason `localhost` stopped working and connecting to `127.0.0.1` seems to fix the problem.
> Fix integration tests getting stuck.

- services/data/postgres_async_db.py
- services/ui_backend_service/tests/integration_tests/status_attempts_test.py
- services/ui_backend_service/tests/integration_tests/tasks_test.py
- uses the last_heartbeat_ts as finished_at timestamp in cases where any other finished timestamp is not available
> Fix finished at timestamp for failed attempts

- services/data/postgres_async_db.py
- services/ui_backend_service/tests/integration_tests/runs_test.py
- services/ui_backend_service/tests/integration_tests/utils.py
- adds a duration for running runs that have no datapoints (missing heartbeat) for deducing the duration. Uses current time and run ts_epoch as a failover.
- extend integration test helpers to be able to approximately assert results that are generated during query execution (`extract(epoch from now())`)
> Add duration and finished at to running meson runs

- services/ui_backend_service/api/task.py
- removes default attempt_id ordering from run_tasks request as unnecessary/confusing.
The UI performs a sort by `ts_epoch ASC` by default, so in order to experience any performance gains, an index for this should be applied. Something along the lines of
```
CREATE INDEX idx_task_v3_ts_epoch_asc ON tasks_v3 (ts_epoch ASC)
```
add this to the migration service in a separate PR if this proves effective in testing.
> fix for run_tasks response ordering and query performance

- services/data/postgres_async_db.py
- services/ui_backend_service/tests/integration_tests/tasks_test.py
- add integration test coverage for task with running status and heartbeat
- fix issue with task finished_at timestamp query
> fix running status task finished_at timestamp

- services/ui_backend_service/api/run.py
- services/ui_backend_service/api/utils.py
- services/ui_backend_service/tests/unit_tests/utils_test.py
Expects index
```CREATE INDEX runs_v3_idx_gin_tags_combined_tsvector ON runs_v3 USING gin (to_tsvector('simple', (tags||system_tags)));```
from PR https://github.com/Netflix/metaflow-service/pull/106
> Add tsvector support for tag filtering to improve performance

- services/data/postgres_async_db.py
- services/ui_backend_service/tests/integration_tests/tasks_test.py
changes task attempt finished_at, status and duration heuristics to account for successive attempts
- if a successive attempt exists, the current attempt status is automatically `failed`
- if no `finished_at` can be determined for current attempt, the `started_at` of the next attempt is used.
- duration is calculated with `finished_at - started_at` always, never relying on task `ts_epoch`
> Fix task attempts finished_at and duration logic to account for successive attempts

- services/ui_backend_service/tests/integration_tests/grouped_runs_test.py
- services/utils/__init__.py
- services/utils/tests/unit_tests/utils_test.py
- change error logging to only happen for unknown generic errors (exclude errors with a custom error-id from logging)
- add unit tests to cover the handle_exceptions wrapper functionality 
- fix flaky grouped_runs test issue.
> Fix: Cleanup error logging in handle_exceptions wrapper and add unit tests

- docker-compose.development.yml
- services/data/postgres_async_db.py
- services/ui_backend_service/api/config.py
- services/ui_backend_service/api/notify.py
This PR is a workaround for PostgreSQL bug in logical replication mode where notifications via triggers were not delivered properly.
Solution here is to manually `NOTIFY ping` channel in intervals so that the main `NOTIFY notify` channel "buffer" is delivered along with the ping channel. It doesn't matter which channel is notified, important thing here is that the notification originates from non-replication source. This bug is present in at least PostgreSQL versions 10 - 13.
`NOTIFY ping` is executed every 1 second, so all replication notifications will be delivered in 1 second intervals in this special use-case.
Read more about the bug here: https://www.postgresql.org/message-id/153243441449.1404.2274116228506175596%40wrigleys.postgresql.org
This PR also enables WAL level `logical` on …
> fix: Enable triggers always and use periodic ping for NOTIFY.

- services/data/postgres_async_db.py
- services/ui_backend_service/api/notify.py
- services/ui_backend_service/data/db/tables/run.py
- services/ui_backend_service/data/db/tables/step.py
- services/ui_backend_service/data/db/tables/task.py
- Adds possibility to configure custom table names (instead of the default `*_v3` ones) through environment variables.
- cleans up `async_postgres_db` from unused variables and false positive pylint warnings.
Possible environment variables are:
`
DB_TABLE_NAME_FLOWS    
DB_TABLE_NAME_RUNS    
DB_TABLE_NAME_STEPS    
DB_TABLE_NAME_TASKS  
DB_TABLE_NAME_METADATA  
DB_TABLE_NAME_ARTIFACT  
`
> feat: DB table name environment variable configuration

- services/ui_backend_service/data/db/tables/task.py
- changes task attempt query from using UNNEST to generate_series, which you can easily provide the end value for in case of fluctuating max_attempts.
> chore: change task attempt query for easier max_attempts config

- services/ui_backend_service/api/heartbeat_monitor.py
- services/ui_backend_service/api/task.py
- services/ui_backend_service/api/ws.py
- services/ui_backend_service/data/cache/store.py
- services/ui_backend_service/data/db/tables/artifact.py
- services/ui_backend_service/data/db/tables/run.py
- services/ui_backend_service/data/refiner/__init__.py
- services/ui_backend_service/data/refiner/parameter_refiner.py
- services/ui_backend_service/data/refiner/refinery.py
- services/ui_backend_service/tests/integration_tests/utils.py
- Introduces new `ParameterRefiner`
- `ParameterRefiner` is now used in `ArtifactCacheStore`
- `GET /flows/{flow_id}/runs/{run_number}/parameters` uses `ArtifactCacheStore` internally
- `CacheStore` table -specific logic moved under `ui_service_backend/data/db/tables/`.
> refactor: Introduce ParameterRefiner to refine Run parameters.

- services/ui_backend_service/api/__init__.py
- services/ui_backend_service/api/autocomplete.py
- services/ui_backend_service/data/db/tables/base.py
- services/ui_backend_service/tests/integration_tests/autocomplete_test.py
- services/ui_backend_service/tests/integration_tests/utils.py
- services/ui_backend_service/ui_server.py
Draft for autocomplete
Autocomplete endpoints:
/autocomplete/tags
/autocomplete/flows
/autocomplete/flows/:flowname/runs
/autocomplete/flows/:flowname/runs/:runid/step
Result for tags endpoint is cached within class and refreshed every 5min since this request might be rather slow to database.
> feat: Autocomplete endpoints for UI

- services/data/postgres_async_db.py
- services/ui_backend_service/api/heartbeat_monitor.py
- services/ui_backend_service/api/notify.py
- services/ui_backend_service/api/ws.py
- services/ui_backend_service/data/db/tables/run.py
- services/ui_backend_service/data/db/tables/task.py
- services/ui_backend_service/tests/integration_tests/notify_test.py
- moves query logic away from heartbeat getters and into db table classes
- add missing import for `time` to run table class
- add docstrings
- add `last_heartbeat_ts` field to be part of Run table trigger message. This completely eliminates the need to do a DB query when adding runs to heartbeat monitoring.
> refactor: move logic from heartbeat classes to db adapter and improve run heartbeat monitoring.

- services/ui_backend_service/data/cache/store.py
- services/ui_backend_service/data/refiner/refinery.py
- services/ui_backend_service/data/refiner/task_refiner.py
Task refiner was passing non-S3 locations to the `GetArtifacts` cache action, which was getting stuck due to the long timeout of `CacheFuture`.
Added a guard to refinery so only valid S3 locations are passed to the cache action, as there is by choice no handling of streamed errors in the fetching.
Also fixed ordering with task refiner no-op guard.
> fix: incorrect task websocket data with local datastore

- services/ui_backend_service/api/admin.py
- services/ui_backend_service/tests/integration_tests/admin_test.py
- rename announcements getter not to collide with instance variable naming
- add integration tests for broken json strings in environment variables.
> fix: polishing announcements

- .gitignore
- Dockerfile.service.test
- MANIFEST.in
- README.md
- docker-compose.test.yml
- pytest.ini
- requirements.dev.txt
- requirements.txt
- services/metadata_service/requirements.txt
- services/metadata_service/tests/integration_tests/placeholder_test.py
- services/migration_service/requirements.txt
- setup.cfg
- setup.py
- tox.ini
- wait-for-postgres.sh
Testing and codestyle enhancements originally introduced in the UI development branch. Aim to merge this before #144 so we can write some integration tests for the metadata service.
This PR omits any pointers to `service.ui_backend` and `services.utils` as these are introduced in future PR's and including missing paths would break the test runner.
Changes: 
* add Tox support and pycodestyle directives
* update .gitignore for tox temp files
* add docker-compose and dockerfile for running tests
* add instructions to README.md for running tests
* add placeholder test for metadata_service
* pin service dependency versions
* add configurable wait time and retry count to postgres server startup waiting.
> feat: running tests with docker-compose and configure codestyles

- services/ui_backend_service/README.md
- services/ui_backend_service/api/admin.py
- services/ui_backend_service/doc.py
You can define notifications that are broadcasted to all clients using the UI by setting an environment variable `NOTIFICATIONS` for the backend process. The value should be a _stringified_ json of the format:
```json
[
{
"created": 1618404534000,
"message": "Upcoming service maintenance"
}
]
```
You can provide as many notifications as necessary, topmost item is considered the latest.
Following attributes are supported:
| Attribute     | Description                                                                       | Default value                                 |
| ------------- | --------------------------------------------------------------------------------- | --------------------------------------------- |
| `id`          | Notification identifier …
> System notifications content-type feature

- services/ui_backend_service/api/dag.py
- uses 'code-package-url' as part of the query for finding code package location
> fix: use internal codepackage name as part of lookup as well.

- services/ui_backend_service/api/dag.py
- correctly handles internal `code-package-url` location as a string instead of json.
> fix: internal code-package fetching

- services/ui_backend_service/requirements.txt
Revert recent changes on UI service `requirements.txt` due to `aiohttp` 3.7 websocket regression.
There are multiple reported issues on websocket behaviour:
- https://github.com/aio-libs/aiohttp/issues/5301
- https://github.com/aio-libs/aiohttp/issues/5212
- https://github.com/aio-libs/aiohttp/issues/5182
- https://github.com/aio-libs/aiohttp/issues/5180
Let's keep these dependencies pinned for now and upgrade each of these in controlled manner later on so we can resume realtime functionality.
> Pin UI service dependencies due to aiohttp websocket regression

- services/ui_backend_service/data/db/tables/step.py
- services/ui_backend_service/data/db/tables/task.py
- services/ui_backend_service/tests/integration_tests/steps_test.py
- services/ui_backend_service/tests/integration_tests/tasks_test.py
- adds current time as a fallback for calculating task and step durations, when no other timestamps exist
> fix: duration logic fallbacks

- services/ui_backend_service/data/cache/generate_dag_action.py
Codepackage 'script' stores the full path for executed script, but only the basename is used for sourcecode storage in the tarball. Changes DAG Parsing to only use the basename for sourcecode lookup
> fix: use basename for script_name in dag parser

- services/ui_backend_service/api/log.py
- services/ui_backend_service/requirements.txt
Fetching logs from s3 with the boto3 library blocks the request handler, affecting other request processing significantly. Change this to use the aioboto3 wrappers to be able to yield execution while waiting for S3 response.
> fix: change blocking boto3 to aioboto3 for log fetching

- services/ui_backend_service/data/cache/client/cache_async_client.py
- services/ui_backend_service/data/cache/client/cache_client.py
- services/ui_backend_service/data/cache/client/cache_server.py
- services/ui_backend_service/data/cache/client/cache_store.py
- services/ui_backend_service/data/refiner/parameter_refiner.py
This PR introduces following changes:
- Prevent `CacheServerUnreachable` fatal error.
- Cache `max_size` is now considered as a soft limit, GC will eventually delete exceeding data after graceful period.
- Keep track of pending cache actions so that `CacheClient` and `CacheFuture` can provide accurate responses.
> UI cache error handling

- services/ui_backend_service/api/log.py
- services/ui_backend_service/doc.py
- services/ui_backend_service/tests/unit_tests/log_test.py
Paginate returned logs to deal with possibly huge log files. Primarily meant to alleviate pressure from the frontend side of handling huge log files in the browser. Backend strain still remains due to having to process the whole log in-memory.
Default `_limit` for log routes is set to 1000 log lines per response, with a maximum of 10000
adds unit tests to cover pagination logic
> feat: paginate log requests

- services/ui_backend_service/data/db/tables/run.py
- services/ui_backend_service/data/db/tables/step.py
- services/ui_backend_service/data/db/tables/task.py
- services/ui_backend_service/tests/integration_tests/runs_test.py
- further refines the cutoff logic in task queries. if a task has remained in a stuck state for two weeks, the duration will count as null instead of falling back on current time calculations.
- also reworks how task query joins are done, cleaning up attempt detection logic and improving performance
some perf test numbers
| Branch | Cost | Planning | Execution |
|-------|-----|--------|----------|
| UI | 42302.23..52876.51 | 1.017 ms | 282.702 ms |
| current | 446.93..447.03 | 1.001 ms | 119.992 ms |
also noteworthy that current query costs remain acceptable with offsets, whereas UI implementation scales poorly with increases in number of records.
> fix: fine tune cutoff logic

- services/ui_backend_service/data/cache/client/cache_async_client.py
- services/ui_backend_service/data/cache/client/cache_server.py
- services/ui_backend_service/data/refiner/parameter_refiner.py
- Increase CacheAsyncClient pipe buffer from 64KB to 1024KB
- Prevent passing of individual artifact keys from subprocess to ensure buffer is not exceeded
This PR is a precautionary measure, actual issue which is the cache limit should not be configured to exceed available disk space. Configured with env variables:
- `CACHE_ARTIFACT_STORAGE_LIMIT`
- `CACHE_DAG_STORAGE_LIMIT`
> CacheAsyncClient increase pipe buffer

- services/ui_backend_service/api/autocomplete.py
- services/ui_backend_service/tests/integration_tests/autocomplete_test.py
Changes the tags autocomplete routes to use in-memory cached tags and list operations for filtering. Backend fetches fresh tags periodically. Initial benchmarks show that this performs immensely better than the query-only approach (~300ms vs 5sec latencies)
> fix: tags autocomplete performance enhancement

- services/ui_backend_service/data/db/tables/base.py
Changes default run cutoff period for detecting failed runs from 14 days down to 6 days
> feat: change default run cutoff to 6 days

- services/ui_backend_service/data/db/tables/base.py
Use value passing with the grouped query as well for proper security/escaping of content
> fix: use value passing to cursor execute for grouped query

- services/ui_backend_service/api/artifact.py
- services/ui_backend_service/api/artifactsearch.py
- services/ui_backend_service/api/dag.py
- services/ui_backend_service/api/run.py
- services/ui_backend_service/api/task.py
- services/ui_backend_service/api/utils.py
- services/ui_backend_service/data/cache/client/cache_action.py
- services/ui_backend_service/data/cache/client/cache_async_client.py
- services/ui_backend_service/data/cache/client/cache_client.py
- services/ui_backend_service/data/cache/client/cache_server.py
- services/ui_backend_service/data/cache/client/cache_worker.py
- services/ui_backend_service/data/cache/generate_dag_action.py
- services/ui_backend_service/data/cache/get_artifacts_action.py
- services/ui_backend_service/data/cache/search_artifacts_action.py
- services/ui_backend_service/data/cache/store.py
- services/ui_backend_service/data/cache/utils.py
- services/ui_backend_service/data/db/tables/artifact.py
- services/ui_backend_service/data/db/tables/base.py
- services/ui_backend_service/data/refiner/artifact_refiner.py
- services/ui_backend_service/data/refiner/parameter_refiner.py
- services/ui_backend_service/data/refiner/refinery.py
- services/ui_backend_service/data/refiner/task_refiner.py
- services/ui_backend_service/doc.py
- services/ui_backend_service/tests/integration_tests/status_attempts_test.py
- services/ui_backend_service/tests/integration_tests/status_tasks_test.py
- services/ui_backend_service/tests/unit_tests/cache_utils_test.py
Cache functionality changes:
- More accurate error results
- Each artifact error result is now returned individually instead of one global error causing whole request to fail
- Added support for streaming errors in real-time
- Added support for cache invalidation via `?invalidate=true` query parameter where results are cacheable
- Timeline search result now includes individual errors instead one global failure with error message for each task
> fix[cache]: Get artifact error report for individual items.

- services/data/postgres_async_db.py
fixes possible table locking issues due to always opting to setup table triggers when deploying the backend service. Changes trigger creation to only happen in case triggers are not present on the table.
> fix: better table trigger setup process

- services/ui_backend_service/data/cache/get_artifacts_action.py
- services/ui_backend_service/data/cache/search_artifacts_action.py
- services/ui_backend_service/data/cache/utils.py
- services/ui_backend_service/docs/environment.md
- services/ui_backend_service/tests/unit_tests/cache_utils_test.py
- services/ui_backend_service/tests/unit_tests/get_artifacts_action_test.py
- moves shared helpers to cache utils, update unit tests accordingly
- removes batching of S3 gets inside cache actions, as the current implementation is completely sequential in the way s3 objects are fetched.
- make `MAX_SIZE` configurable via environment variables, as the default 4kb limit is quite arbitrary.
- update docs
> chore: cache cleanup and configuration

- services/ui_backend_service/api/log.py
- services/ui_backend_service/data/cache/generate_dag_action.py
- services/ui_backend_service/data/cache/get_artifacts_action.py
- services/ui_backend_service/data/cache/search_artifacts_action.py
- services/ui_backend_service/data/cache/utils.py
Two new environment variables for UI service:
- `METAFLOW_S3_ENDPOINT_URL`
- `METAFLOW_S3_VERIFY_CERTIFICATE`
This change is similar to Metaflow boto3 client init https://github.com/Netflix/metaflow/blob/dc42d670e6c3f7555f40290fce6ed46eb0c12b17/metaflow/datastore/util/s3util.py#L19
> feat[s3]: Customize S3 client endpoint url as well as SSL verify flag

- services/ui_backend_service/data/cache/get_artifacts_action.py
`GetArtifacts` -action: Fix problem when unpacking more than 2 values from cache. This only affected error responses where it contained more than 2 values: `success,value,detail`.
> fix[cache]: Fix problem when unpacking more than 2 values from cache.

- services/ui_backend_service/api/notify.py
- services/ui_backend_service/data/cache/store.py
- services/ui_backend_service/data/db/tables/artifact.py
- services/ui_backend_service/data/db/tables/run.py
- change how artifact locations are fetched for runs when preloading data, make sure the query uses an index on artifact table
> fix: make sure artifact preload query uses index

- services/ui_backend_service/README.md
- services/ui_backend_service/frontend.py
Adds ability to inject content to `index.html` when serving UI (with `UI_ENABLED=1` env variable).
Introduces following env variables:
- `METAFLOW_HEAD` - Inject content to `head` element
- `METAFLOW_BODY_BEFORE` - Inject content at the beginning of `body` element
- `METAFLOW_BODY_AFTER` - Inject content at the end of `body` element
Use case for these variables ranges from additional meta tags to analytics script injection.
Example on how to add keyword meta tag to Metaflow UI:
```
METAFLOW_HEAD='<meta name="keywords" content="metaflow" />'
```
> feat: Add ability to inject head/body content when serving UI

- services/ui_backend_service/api/notify.py
Related to PR https://github.com/Netflix/metaflow-service/pull/132
Prefer NOTIFY notify instead of ping to ensure messages are always consumed. This is experimental fix to try to overcome a bug on pg_notify while using logical replication.
Following messages were observed on PostgreSQL logs against logical replication (subscription) instance:
```
ERROR: too many notifications in the NOTIFY queue
STATEMENT: NOTIFY ping
WARNING: NOTIFY queue is 100% full
```
> fix: Switch pg_notify ping channel to notify

- Dockerfile
Pinning the go docker dependency otherwise the image is not building; Ran into some issue with `go:latest` image so pinning the working image.
> Pinning Go Dep in docker file.

- services/ui_backend_service/data/db/tables/base.py
- services/ui_backend_service/data/db/tables/run.py
- services/ui_backend_service/tests/integration_tests/grouped_runs_test.py
- services/ui_backend_service/tests/integration_tests/runs_test.py
- services/ui_backend_service/tests/integration_tests/status_runs_test.py
- remove unnecessary fallback to end step _task_ok artifact for run status inference
- rely solely on run heartbeat and attempt/attempt_ok metadata entries for status, duration and finished_at timestamp
- update integration tests to reflect changes
- Also solves incorrect status for runs during end-step retries.
> fix: streamline run statuses and remove fallbacks

- services/ui_backend_service/api/log.py
- services/ui_backend_service/api/utils.py
- services/ui_backend_service/data/cache/client/cache_worker.py
- services/ui_backend_service/data/cache/get_log_file_action.py
- services/ui_backend_service/data/cache/store.py
- services/ui_backend_service/data/cache/utils.py
- services/ui_backend_service/requirements.txt
- services/ui_backend_service/tests/integration_tests/log_test.py
- services/ui_backend_service/tests/unit_tests/log_test.py
- services/ui_backend_service/tests/unit_tests/utils_test.py
- services/ui_backend_service/ui_server.py
- adds total page count to log api responses
- reverses the log lines default order to: from oldest to newest
- adds support for `?_order=-row` query param for reversing log order if necessary
- update tests
- adds cache layer to log fetching in order to reduce latency caused by unnecessarily refetching logs from S3 datastore
- change cache workers to skip re-writing key values to disk in case existing values are identical to new ones.
- remove aiobotocore dependency
> feat: log improvements

- Dockerfile
UI Service is not started automatically and will be used separately by overwriting CMD.
This change is relevant to upcoming Netflix/metaflow-tools repository's Cloudformation changes.
> Include UI service as part of main Dockerfile

- Dockerfile.service.test
golang:latest has issues with the goose installation for whatever reason. Pinning the version fixes this and the docker image build successfully.
Change is more in line with the other Dockerfiles also having the version pinned.
> fix: pin test Dockerfile golang dependency

- services/data/postgres_async_db.py
- services/ui_backend_service/requirements.txt
Unpin metaflow client version from ui_service requirements, as the service should always work with latest client version.
Keep a lower bound to guard against installing unsupported versions though.
> chore: unpin metaflow version from ui_backend_service

- services/data/postgres_async_db.py
- services/ui_backend_service/api/ws.py
fixes issues related to web socket holding on to stale connections in subscriptions, and the resource broadcast method not having any handling for possible exceptions thrown by trying to write to a closing transport.
exhibited as an issue where UI was not receiving realtime updates, but only in cases where there was a *preceding* 'closing' subscription when broadcasting resource updates.
also fixes an issue with passing 'since' to websocket subscription not being handled correctly. create_task was incorrectly being passed an awaited coroutine
> fix: websocket disconnect and broadcast issues

- services/ui_backend_service/data/cache/get_log_file_action.py
- services/ui_backend_service/tests/unit_tests/get_log_file_action_test.py
MFLOG type logs can have missing timestamps, where the tuple from the metaflow client does not always return a datetime object as part of the logline. Fix log cache action to handle this safely
> fix: handle missing mflog timestamps

- services/ui_backend_service/data/__init__.py
- services/ui_backend_service/data/cache/get_artifacts_action.py
- services/ui_backend_service/data/cache/get_data_action.py
- services/ui_backend_service/data/cache/search_artifacts_action.py
- services/ui_backend_service/data/cache/utils.py
- services/ui_backend_service/data/refiner/refinery.py
- services/ui_backend_service/tests/unit_tests/cache_utils_test.py
- services/ui_backend_service/tests/unit_tests/data_test.py
add helpers for cache actions to unify the value storage for artifacts and non-recoverable exceptions
adds unit tests to cover helpers, and the previously introduced `streamed_errors` contextmanager
refactors value unpacking helper to a common module as it is shared among a few components.
> chore: add cache helpers and refactor value storage

- services/ui_backend_service/data/cache/generate_dag_action.py
code package access (which fails for R flows due to KeyError) was left outside the try/except block that raises a custom error for unsupported flow language. Refactor `generate_dag` to take in a Run instance, and perform code package accessing inside it to correctly except the error.
> fix: catch unsupported DAG language case correctly

- services/ui_backend_service/api/log.py
- services/ui_backend_service/data/cache/client/cache_client.py
*Issue*
Under certain circumstances the cache futures .get() can be accessed even though an async with block is used for capturing streamed errors. This can happen for example with cache actions that throw an exception quickly, removing themselves from pending requests immediately afterwards. More often than not the `wait_iter` did not have time to find the file on disk and read its contents before `has_pending_request()` starts returning false again, completely breaking out of stream iteration.
*Change*
introduces a fixed curfew for when a stream file should appear on disk, and trying to access this despite no pending request existing anymore. Also introduces a guard for log routes against possible `None` being returned  despite the fixes, due to other underlying issues with the cache …
> fix: cache timing issue, returning none

- services/metadata_service/api/utils.py
The calling function doesn't pass the `traceback_str` argument to the `http_500` function in  `services.metadata_service.api.utils`; This makes the `traceback_str` to be what is set during import. 
This will PR resolves this by dynamically getting the traceback when it is not added in the function. ( as it is in `services.metadata_service.api.utils.handle_exception`
> Fixing how `traceback_str` is set in `http_500` function

- services/data/db_utils.py
- services/metadata_service/api/artifact.py
Users of metaflow after upgrading the service were getting `500` Errors when they try to access Data for task related to some flow; They managed to access metadata though. Slack Thread with more context : https://outerboundsco.slack.com/archives/C02116BBNTU/p1636723735291800
The Debug logs from the MD service looked like the following :
```
2021-12-10 08:13:18.782,ERROR:aiohttp.server:Error handling request
2021-12-10 08:13:18.782,Traceback (most recent call last):
2021-12-10 08:13:18.782,"  File ""/opt/latest/lib/python3.7/site-packages/aiohttp/web_protocol.py"", line 435, in _handle_request"
2021-12-10 08:13:18.782,    resp = await request_handler(request)
2021-12-10 08:13:18.782,"  File ""/opt/latest/lib/python3.7/site-packages/aiohttp/web_app.py"", line 504, in _handle"
2021-12-10 …
```
> Gracefully handling db failure for `/artifacts` API

- requirements.dev.txt
temporarily pin pytest-aiohttp to v0.3.0 due to unexpected issues with latest versions.
> fix: pin problematic test dependency

- services/ui_backend_service/api/utils.py
I have had a lot of problems with setting the PLUGINS environment variable, which requires a JSON string as its value.
This PR adds some extra logging to the JSON decoding to aid in debugging when the supplied JSON is poorly formed.
(copied from other branch off valay's fork)
> Moving logging change to branch off Netflix

- services/metadata_service/server.py
- services/migration_service/api/utils.py
- services/migration_service/migration_server.py
- services/ui_backend_service/ui_server.py
Omit subapp metadata service swagger docs from ui backend service, as this is included for "internal" use only, and does not need to be documented as part of the public api.
Also clean up wildcard and unused imports from the three services.
> chore: omit subapp swaggerdocs from ui_backend.

- requirements.dev.txt
- services/metadata_service/requirements.txt
- services/metadata_service/tests/integration_tests/artifact_test.py
- services/metadata_service/tests/integration_tests/flow_test.py
- services/metadata_service/tests/integration_tests/metadata_test.py
- services/metadata_service/tests/integration_tests/run_test.py
- services/metadata_service/tests/integration_tests/step_test.py
- services/metadata_service/tests/integration_tests/task_test.py
- services/metadata_service/tests/integration_tests/utils.py
- services/migration_service/requirements.txt
- services/ui_backend_service/requirements.txt
- services/ui_backend_service/tests/integration_tests/admin_test.py
- services/ui_backend_service/tests/integration_tests/artifact_test.py
- services/ui_backend_service/tests/integration_tests/autocomplete_test.py
- services/ui_backend_service/tests/integration_tests/features_test.py
- services/ui_backend_service/tests/integration_tests/flows_test.py
- services/ui_backend_service/tests/integration_tests/grouped_runs_test.py
- services/ui_backend_service/tests/integration_tests/log_test.py
- services/ui_backend_service/tests/integration_tests/metadata_test.py
- services/ui_backend_service/tests/integration_tests/notify_test.py
- services/ui_backend_service/tests/integration_tests/plugins_test.py
- services/ui_backend_service/tests/integration_tests/runs_test.py
- services/ui_backend_service/tests/integration_tests/status_attempts_test.py
- services/ui_backend_service/tests/integration_tests/status_runs_test.py
- services/ui_backend_service/tests/integration_tests/status_tasks_test.py
- services/ui_backend_service/tests/integration_tests/steps_test.py
- services/ui_backend_service/tests/integration_tests/tasks_test.py
- services/ui_backend_service/tests/integration_tests/utils.py
- services/ui_backend_service/tests/integration_tests/ws_test.py
Pins some of the major versions of dependencies
- aiohttp
- aiohttp-swagger
- pytest-aiohttp
Also includes a major clean up to integration tests of all services as `pytest-aiohttp` introduced automatic async fixtures, removing the need to manually interact with the loop when setting up the app for testing.
> chore: pin dependencies and use new pytest aiohttp fixtures

- services/ui_backend_service/api/dag.py
- services/ui_backend_service/api/notify.py
- services/ui_backend_service/data/cache/store.py
- services/ui_backend_service/data/db/tables/artifact.py
- services/ui_backend_service/data/db/tables/metadata.py
- services/ui_backend_service/data/db/utils.py
Fixes unnecessarily eager DAG preloading that happens during service launch. Previous implementation was agnostic whether a run can have a DAG or not, and was calling the cache action regardless, resulting in some unnecessary errors in service log.
Also refactors some of the DAG existence checking logic to the db layer.
> fix: Unnecessarily eager dag preload

- services/ui_backend_service/requirements.txt
It was always missing but it was a transitive dep through `metaflow` package. Now `metaflow` vendors in `click` so it no longer depends on it.
> Add missing click dependency

- services/migration_service/api/utils.py
- services/migration_service/get_virtual_env.py
- services/migration_service/run_script.py
This doesn't really fix anything but more of a QOL improvement so that various exit codes and errors are properly passed through and not swallowed by migrations code.
> Better exit code handling in migrations code

- services/data/postgres_async_db.py
- services/ui_backend_service/data/db/tables/artifact.py
- services/ui_backend_service/data/db/tables/base.py
- services/ui_backend_service/data/db/tables/flow.py
- services/ui_backend_service/data/db/tables/metadata.py
- services/ui_backend_service/data/db/tables/run.py
- services/ui_backend_service/data/db/tables/step.py
- services/ui_backend_service/data/db/tables/task.py
- services/ui_backend_service/tests/integration_tests/utils.py
For some historical reason it looks like there are two ways the db tables are created: through Goose migrations, and some bespoke Python code. These two conflict; in some deployments they race and leave db in a state that is no longer upgradeable by Goose.
This PR removes these bespoke migrations, leaving goose the only way to manage schema.
> Remove table creation from python code

- services/metadata_service/requirements.txt
- services/metadata_service/server.py
- services/migration_service/migration_server.py
- services/migration_service/requirements.txt
- services/ui_backend_service/requirements.txt
- services/ui_backend_service/ui_server.py
`aiohttp-swagger` has a dep with [RCE](https://nvd.nist.gov/vuln/detail/CVE-2021-23369). While I don't believe it affects metaflow-service, it also doesn't seem like these swagger docs are actively used by anyone. So for now I'm thinking we can simply remove that stuff.
I'm not removing swagger definitions for API calls themselves -- there is a chance that we'll bring it back later, or we may validate against them as part of the test suite.
> Remove aiohttp-swagger

- run_goose.py
For context, this script is only used in Helm charts today
> Add an option to goose runner to run migrations only if db is empty

- .github/workflows/test.yml
- services/ui_backend_service/data/cache/client/cache_server.py
- services/ui_backend_service/data/cache/store.py
- services/ui_backend_service/data/db/tables/base.py
- services/ui_backend_service/tests/integration_tests/log_test.py
- services/ui_backend_service/tests/unit_tests/cache_utils_test.py
- tox.ini
Adds an extra step CI to run pylint.  Show errors only.  Minimal modifications to get pylint initially pass.
> introduce automatic pylint to CI

- services/data/postgres_async_db.py
- services/metadata_service/api/run.py
- services/metadata_service/tests/integration_tests/run_test.py
- services/metadata_service/tests/integration_tests/utils.py
This is part of project to add tag mutation support. RFC [here](https://www.notion.so/outerbounds/RFC-Implementing-tag-mutation-98ef6ba39aee4aeeb9c6150b4cffea2a) (see "Tagging CLI").
The new Metaflow client API (which tagging CLI will use) will call this new metadata service endpoint:
```
app.router.add_route("PATCH",
"/flows/{flow_id}/runs/{run_number}/tag/mutate",
```
Some requirements:
- A - Tag changes should be atomic (e.g. we can add/remove multiple tags at once).
- B - Tag changes should not be lost for any concurrent requests.
- C - Fail if mutation is invalid w.r.t. to current tag content (e.g. system tags)
We implement tag updates in the most straightforward manner. In DB terms:
- Check mutation request inputs (without needing current run state)
- Start DB transaction - …
> [tag-mutation-project] Add tag mutation endpoint for Runs to metadata service

- services/data/postgres_async_db.py
- services/metadata_service/api/run.py
- services/metadata_service/tests/integration_tests/run_test.py
The `/tag/mutate` is expected to return a JSON response:
```
{
"tags": LIST_OF_LATEST_TAGS_AFTER_MUTATION
}
```
We erroneously serialized the JSON object one too many times on the way out.  This is the fix.
> [tag-mutation-project] Tag mutation endpoint fix for double JSON encoding

- services/ui_backend_service/requirements.txt
UI backend service to use the latest Metaflow release (which includes Azure support).
We also add Azure pip dependencies. A small amount of bloat, but beats creating new Docker images / tags for with/without Azure.
Note for default S3 support, Metaflow pip package bundles it by default already.
> [Azure support] Support Azure artifacts in UI backend service

- services/ui_backend_service/data/cache/get_cards_action.py
- services/ui_backend_service/data/cache/get_log_file_action.py
- services/ui_backend_service/docs/environment.md
- services/ui_backend_service/tests/unit_tests/get_log_file_action_test.py
Introduces three new environment variables to influence cards and logs loading behavior:
`MF_LOG_LOAD_POLICY`
- `full` (default): loads entire log, matches existing behavior.
- `tail`: loads the tail of the log only (up to fixed size by number of characters).
- `blurb_only`: does not load the log at all. Instead return Python code snippet to access logs using Metaflow client.
`MF_LOG_LOAD_TAIL_SIZE`
Defaults to 100*1024.  Applies when `MF_LOG_LOAD_POLICY=tail`.  Returns the last N lines of the log file, where N is maximized without returning more than `MF_LOG_LOAD_TAIL_SIZE` number of characters.
`MF_CARD_LOAD_POLICY`
* `full` (default): Loads all cards, matches existing behavior.
* `blurb_only`: does not load cards at all.  Instead return Python code snippet to access cards using …
> [UI backend] New options to restrict cards / logs loading

- Dockerfile
addresses vulnerabilities reported by Snyk scans
- update base image of the release image Dockerfile
- update goose to latest version and clean up install commands in dockerfile
some high severity issues remain due to no upgrades available for the base `buster` image, and any further steps would require moving from python 3.7 to a higher version, requiring more extensive testing. These vulnerabilities should not be affecting the actual runtime code though.
> fix: update release image dependencies

- .github/workflows/test.yml
- try to get rid of `FATAL:  role "root" does not exist` in test workflow Stop Container step.
> fix: GitHub test workflow stop containers issues

- pytest.ini
- requirements.dev.txt
- services/ui_backend_service/api/notify.py
- services/ui_backend_service/data/cache/client/cache_async_client.py
- services/ui_backend_service/plugins/__init__.py
- services/ui_backend_service/tests/integration_tests/notify_test.py
- services/ui_backend_service/tests/integration_tests/ws_test.py
- services/ui_backend_service/tests/unit_tests/cache_utils_test.py
- services/utils/__init__.py
fixes use of some deprecated features
- Removes use of deprecated `loop` fixture with aiohttp tests, as of pytest-aiohttp >= 1 this is not necessary.
- use `logger.warning`
- Use packaging.version instead of distutils. unit tests should already cover the expected behavior which previously depended on `LooseVersion`
- rename `TestArtifact` mock class so pytest does not erroneously consider it a test case (has had no effect besides a warning until now).
> chore: fix deprecations

- services/metadata_service/server.py
- services/migration_service/migration_server.py
Use aiohttp AppRunner as the preferred way of setting up a service process as `make_handler()` is deprecated. Affected services are only the metadata and migration service, as ui_backend is already using newer way.
Not in any way critical, as the deprecated method is still part of the library as well. Consider merging at some point as cleanup.
Fixes #197
> chore: fix deprecated way of initialising aiohttp app in services

- .github/workflows/test.yml
- Dockerfile
- Dockerfile.metadata_service
- Dockerfile.migration_service
- Dockerfile.service.test
- Dockerfile.ui_service
- run_goose.py
- services/ui_backend_service/requirements.txt
- services/ui_backend_service/tests/unit_tests/custom_flowgraph_test.py
- setup.py
- tox.ini
In preparation for Python 3.7 being End-of-Life, update the Python version used for all the services Docker images
Addresses #352 
TODO:
> chore: update python version

- services/ui_backend_service/requirements.txt
Addresses https://github.com/Netflix/metaflow-service/issues/375
Adding `google-cloud-storage` dependencies to the UI backend service, so that viewing task logs and DAG structure no longer breaks when these artifacts are stored on GCS.
> Add Google Cloud dependencies to UI backend service (#375)

- Dockerfile
- Dockerfile.metadata_service
- Dockerfile.migration_service
- Dockerfile.service.test
- Dockerfile.ui_service
- docker-compose.development.yml
Context:
The docker build would fail on an M1 laptop with error messages like
```
Building wheels for collected packages: psycopg2
30.95   Building wheel for psycopg2 (setup.py): started
33.66   Building wheel for psycopg2 (setup.py): finished with status 'error'
33.71   error: subprocess-exited-with-error
33.71   
33.71   × python setup.py bdist_wheel did not run successfully.
33.71   │ exit code: 1
33.71   ╰─> [33 lines of output]
33.71       running bdist_wheel
33.71       running build
33.71       running build_py
33.71       creating build
33.71       creating build/lib.linux-x86_64-cpython-311
33.71       creating build/lib.linux-x86_64-cpython-311/psycopg2
33.71       copying lib/errorcodes.py -> build/lib.linux-x86_64-cpython-311/psycopg2
33.71       copying lib/errors.py -> …
```
> Docker changes to support M1 laptops

- .github/workflows/dockerimage.yml
This `dockerimage` action in this repository is using old versions of `checkout` & `build-push-action`. 
This is causing some warnings during the actions. (See [here](https://github.com/Netflix/metaflow-service/actions/runs/5685654496) for more details.) This includes a warning `The following actions uses node12 which is deprecated and will be forced to run on node16`.
This PR updates the versions of `checkout` & `build-push-action` used in the `dockerimage` action. 
Due to the age of the old versions, to obtain like-for-like functionality the upgrade requires the additional use of `metadata-action`, `setup-buildx-action` & `login-action` actions.
> Upgrade Github actions used in `dockerimage` action

- services/metadata_service/api/utils.py
- services/utils/__init__.py
deprecated `pkg_resources` is blocking the execution of tests locally for whatever reason. Change to the preferred `importlib.metadata` fixes this.
> chore: deprecated pkg_resources

- services/ui_backend_service/data/db/tables/run.py
This remediates this by considering a run 'failed' if the hb hasn't been updated within heartbeat_cutoff time as opposed to the heartbeat_threshold time
> In a previous commit, the detection of a failure became too aggressive.

- services/ui_backend_service/data/db/tables/base.py
- services/ui_backend_service/data/db/tables/run.py
- services/ui_backend_service/docs/environment.md
Changes the Run inactive cutoff time default to 6 minutes from 1 day. After the latest query changes this is used to determine whether a run heartbeat is expired or not.
This will give runs that have tasks stuck in a scheduler the 6 minutes grace period for any of them to launch, after which the run level heartbeat will expire and mark the run as failed. If a task starts after this, the run would flip back to `running` status, otherwise remaining `failed` (correctly)
Having to wait a whole day for runs to be marked as failed by default is such a huge departure from the way the UI used to display failed runs that this change is proposed as a possible middle-ground instead of reverting the query changes from #338 .
> fix: tone down run inactive cutoff default

- .github/workflows/dockerimage.yml
- run_goose.py
- services/data/postgres_async_db.py
- services/metadata_service/api/utils.py
- services/metadata_service/server.py
- services/ui_backend_service/data/db/tables/base.py
- services/ui_backend_service/data/db/tables/run.py
- services/ui_backend_service/docs/environment.md
- services/utils/__init__.py
- services/utils/tests/unit_tests/utils_test.py
- tox.ini
fix conflicts with master and addressing some review comments
> Patch pjoshi aurora

- Dockerfile
remove v1_0_1 virtual environment from Dockerfile as it should not be required, and the bundled code contains vulnerabilities that are raising some warnings
> fix: remove legacy virtualenv from Dockerfile

- Dockerfile
- setup.py
Reverting the removal of `/opt/v_1_0_1` virtual environment from the released Docker image for further discussion.
Also reverting version bump of unreleased 2.4.6.
> chore: revert bundle fix for further discussion

- services/ui_backend_service/data/cache/client/cache_async_client.py
- services/ui_backend_service/data/cache/client/cache_server.py
- services/ui_backend_service/data/cache/get_log_file_action.py
- services/ui_backend_service/tests/unit_tests/get_log_file_action_test.py
- Recreate the multiprocess pool at a regular cadence to avoid memory leaks
- Since the pool was never removed it resulted in unbounded growth of memory.
- Added a log size constraint to the `tail` based Log cache setting.
> [cache-memory-leak] Fix Memory leak in cache server

- docker-compose.development.yml
- services/ui_backend_service/api/log.py
- services/ui_backend_service/data/cache/client/cache_action.py
- services/ui_backend_service/data/cache/client/cache_client.py
- services/ui_backend_service/data/cache/client/cache_server.py
- services/ui_backend_service/data/cache/client/cache_store.py
- services/ui_backend_service/data/cache/generate_dag_action.py
- services/ui_backend_service/data/cache/get_data_action.py
- services/ui_backend_service/data/cache/get_log_file_action.py
- services/ui_backend_service/data/cache/search_artifacts_action.py
- services/ui_backend_service/tests/integration_tests/log_test.py
- services/ui_backend_service/tests/unit_tests/get_log_file_action_test.py
Alternative approach to streaming massive logs. Does not require any changes to Metaflow client side.
Intended to supersede #423 
TODO:
> feature: massive logs streaming

- services/data/postgres_async_db.py
this adds versioning to table triggers created by the ui_service.
triggers will now have a timestamp as part of their name, and as part of the trigger setup process when launching the ui_backend it will attempt to clean up table triggers and trigger functions that do not have the correct timestamp (or lack one completely) but otherwise match our trigger naming schema.
Custom triggers not set up by the ui_backend will remain untouched by the changes
> feature: version table triggers

- services/ui_backend_service/api/notify.py
fixes run status 'failed' ending up as final due to heartbeat changes.
new task entries will now also refresh run heartbeat tracking and broadcast latest status
> fix: run status stuck as failed with heartbeat changes

- services/metadata_service/tests/unit_tests/task_test.py
- services/utils/__init__.py
changes to treat unparseable client versions as heartbeat-enabled clients by defaults
also cleanup a rogue debug print
> feature: treat client version parse failures as heartbeat-enabled by default

- services/data/models.py
- services/data/postgres_async_db.py
- services/metadata_service/api/task.py
- services/metadata_service/api/utils.py
- services/metadata_service/tests/integration_tests/task_test.py
adds ability to filter tasks by metadata via
```
GET /flows/{flow_id}/runs/{run_id}/steps/{step_name}/filtered_tasks?metadata_field_name=some-field
GET /flows/{flow_id}/runs/{run_id}/steps/{step_name}/filtered_tasks?pattern=some-value
GET /flows/{flow_id}/runs/{run_id}/steps/{step_name}/filtered_tasks?metadata_field_name=some-field&pattern=some-.*
```
API up for discussion. Required in order to enable https://github.com/Netflix/metaflow/pull/2124
> feature: add task filtering based on metadata
