metadata_service/api/artifact.py
metadata_service/data/postgres_async_db.py

ensures that only the artifacts from the latest attempt are returned
see github issue:
https://github.com/Netflix/metaflow/issues/201

only return artifacts from latest attempt

---

.github/workflows/dockerimage.yml
Dockerfile
Dockerfile.metadata_service
Dockerfile.migration_service
docker-compose.yml
metadata_service/api/__init__.py
metadata_service/api/utils.py
migration_service/api/__init__.py
migration_service/api/admin.py
migration_service/api/utils.py
migration_service/data/postgres_async_db.py
migration_service/get_virtual_env.py
migration_service/migration_files/1_create_tables.sql
migration_service/migration_files/20200603104139_add_str_id_cols.sql
migration_service/migration_server.py
migration_service/requirements.txt
migration_service/run_script.py

Adds a standalone migration service to help manage db schema upgrades

packaging changes and addition of migration service

---

migration_service/migration_files/1_create_tables.sql

check existence of tables before attempting to create them otherwise upgrade may fail in some cases and a downgrade may result in getting stuck

only create tables if they dont already exist

---

migration_service/api/__init__.py
migration_service/api/admin.py
migration_service/api/utils.py
migration_service/data/postgres_async_db.py
migration_service/migration_config.py

Migration Service
- unify code for reading configs into single file
- escape special characters in config
- properly handle retry logic

escape special characters and properly handle retries

---

services/data/models.py
services/data/postgres_async_db.py
services/metadata_service/api/run.py
services/metadata_service/api/task.py

adding heartbeat endpoints for task and run
testing still required

add hb endpoints

---

services/ui_backend_service/cache/generate_dag_action.py
services/ui_backend_service/doc.py

* Adds error for DAG parsing of R-language code package

Add unsupported language dag parsing error

---

services/data/models.py
services/data/postgres_async_db.py
services/ui_backend_service/api/data_refiner.py
services/ui_backend_service/cache/get_artifacts_action.py
services/ui_backend_service/doc.py

* Adds the foreach stack data from S3 to foreach step tasks
* fixed issue with get_artifacts_action failing with some malformed locations.

Add foreach stack to tasks

---

services/ui_backend_service/cache/generate_dag_action.py

* Fixes box_next value in dag generation.

Fix box_next logic in generate_dag

---

services/ui_backend_service/api/data_refiner.py
services/ui_backend_service/doc.py
services/ui_backend_service/tests/integration_tests/notify_test.py
services/ui_backend_service/tests/integration_tests/tasks_test.py

* moves the generation of a label for foreach step tasks to the backends postprocessing.
* updates related tests

Generate foreach_label in task postprocessing step

---

services/data/postgres_async_db.py
services/ui_backend_service/tests/integration_tests/runs_test.py

* adds finished_at timestamp to failed runs as well to help with sorting runs

Add finished at to failed runs

---

services/ui_backend_service/cache/generate_dag_action.py

* fixes error with missing 'use_r' key in codepackage causing DAG generation errors.

Fix dag generation R language check error

---

.github/workflows/test.yml
services/metadata_service/api/task.py
services/migration_service/api/__init__.py
services/migration_service/api/utils.py
services/migration_service/get_virtual_env.py
services/migration_service/run_script.py
services/ui_backend_service/api/admin.py
services/ui_backend_service/api/artifactsearch.py
services/ui_backend_service/api/heartbeat_monitor.py
services/ui_backend_service/api/notify.py
services/ui_backend_service/api/run.py
services/ui_backend_service/api/task.py
services/ui_backend_service/api/utils.py
services/ui_backend_service/api/ws.py
services/ui_backend_service/cache/custom_flowgraph.py
services/ui_backend_service/cache/generate_dag_action.py
services/ui_backend_service/cache/get_artifacts_action.py
services/ui_backend_service/cache/search_artifacts_action.py
services/ui_backend_service/cache/store.py
services/ui_backend_service/cache/utils.py
services/ui_backend_service/doc.py
services/ui_backend_service/frontend.py
services/ui_backend_service/tests/integration_tests/utils.py
services/utils/__init__.py

* fixes PEP8 code style errors in metadata_service, migration_service, ui_backend_service and services/utils
* disable continue-on-error for codestyle test

Codestyle fixes

---

services/ui_backend_service/api/heartbeat_monitor.py
services/ui_backend_service/api/ws.py

* Add guard to heartbeat monitor against failing to fetch broadcastable records.
* Fixes regression from earlier websocket broadcast refactoring related to heartbeat monitor broadcasts.

adding guards for heartbeat monitor load and broadcast

---

docker-compose.development.yml
services/data/postgres_async_db.py

Log all exceptions including stacktraces.
Also introduces echo mode for aiopg using `AIOPG_ECHO=1` environment variable (defaults to `0`).

Improved logging for postgres_async_db.py

---

services/ui_backend_service/cache/store.py

* fixes regression from changing to ExecutorEventEmitter

fix regression from switching to ExecutorEventEmitter

---

services/ui_backend_service/README.md
services/ui_backend_service/cache/store.py

* Adds configurable CACHE_ARTIFACT_STORAGE_LIMIT, and CACHE_DAG_STORAGE_LIMIT to control storage reserved for cache.
* Update README on configurable Cache store environment variables
* add tag for cache store logs for further visibility.

Add configurable cache limits and tags for cache logs.

---

services/ui_backend_service/api/ws.py

* Adds a handler to websocket connections for custom ping messages from the client side

Add custom ping support to websocket handler

---

services/ui_backend_service/cache/get_artifacts_action.py
services/ui_backend_service/cache/search_artifacts_action.py

* Fixes errors in cache actions when trying to serialize artifacts of incompatible types.

fix json type errors in artifact cache actions.

---

services/ui_backend_service/api/utils.py

UI: Fix error with pagination when errors are raised during query execution

UI pagination error

---

services/data/postgres_async_db.py
services/ui_backend_service/api/notify.py
services/ui_backend_service/api/ws.py
services/ui_backend_service/cache/store.py

* Adds some identifying tags to websocket and notify exception logs
* fixes websocket pong response not being included inside try catch
* change all logging to use the env var configured services.utils.logging

Add tags to logs and fix ws trycatch

---

services/ui_backend_service/cache/get_artifacts_action.py
services/ui_backend_service/cache/search_artifacts_action.py
services/ui_backend_service/tests/unit_tests/get_artifacts_action_test.py
services/ui_backend_service/tests/unit_tests/search_artifacts_action_test.py

* fix get and search artifact cache actions depending on s3 locations order for cache key generation
* add unit tests for cache key generators.

Fix some cache keys depending on location ordering

---

services/ui_backend_service/api/data_refiner.py
services/ui_backend_service/api/notify.py

* add logging to data refiner cache failures
* use tagged logger for notify

More logging additions

---

services/ui_backend_service/cache/store.py

- changes default cache diskspace limits to be dynamic, depending on the size of the disk.

change default cache storage limits to depend on disk size

---

services/ui_backend_service/api/admin.py
services/ui_backend_service/tests/integration_tests/admin_test.py

- update admin link labels and add gitter link instead of github

update admin links.

---

services/data/postgres_async_db.py

- increases heartbeat threshold to three times the heartbeat interval.

Increase heartbeat_ts threshold limit

---

services/ui_backend_service/tests/integration_tests/utils.py

- fixes test assert helper output to be more detailed in case of a failed test

fix resource assert helpers to have more detailed fail messages.

---

services/ui_backend_service/cache/store.py

- adds `script_name` to list of ignored parameters

add 'script_name' to ignored parameters

---

services/ui_backend_service/api/task.py
services/ui_backend_service/data/refiner/refinery.py
services/ui_backend_service/tests/integration_tests/status_attempts_test.py
services/ui_backend_service/tests/integration_tests/status_tasks_test.py

- fixes task integration tests that were broken after the refactor branch got merged

Fix broken integration test

---

services/data/db_utils.py
services/data/postgres_async_db.py
services/ui_backend_service/api/utils.py
services/ui_backend_service/doc.py
services/ui_backend_service/tests/unit_tests/utils_test.py

Remove `COUNT(*) OVER() AS count_total` from API queries due to performance impact.

Remove pagination last page due to performance impact

---

services/data/models.py
services/data/postgres_async_db.py
services/ui_backend_service/README.md
services/ui_backend_service/api/run.py
services/ui_backend_service/api/utils.py
services/ui_backend_service/tests/integration_tests/runs_test.py
services/ui_backend_service/tests/unit_tests/utils_test.py

Rename `real_user` column to `user` column.

Rename real_user column to user column

---

services/ui_backend_service/api/utils.py

Safely handle `pagination=None` situation.

Handle DBPagination object when it is None.

---

services/data/postgres_async_db.py
services/ui_backend_service/tests/integration_tests/runs_test.py

Consider `SFN` user as `NULL` instead of comparing against `system_tags` column.

SFN user considered NULL

---

.github/workflows/test.yml
services/data/models.py
services/data/postgres_async_db.py
services/ui_backend_service/api/run.py
services/ui_backend_service/tests/integration_tests/runs_test.py

```sql
COALESCE(run_id, run_number::text) AS run
```
Also, prefer string concat over `CONCAT()` function to make indexing simpler.

Introduce new column 'run' for runs_v3 

---

services/ui_backend_service/api/log.py

- change regex strings to be raw bytestrings as intended to avoid codestyle alerts.
- fix some formatting issues.

Fix pycodestyle alerts

---

services/ui_backend_service/api/run.py
services/ui_backend_service/api/utils.py
services/ui_backend_service/tests/unit_tests/utils_test.py

Reverts Netflix/metaflow-service#120

Revert "Add tsvector support for tag filtering to improve performance"

---

services/ui_backend_service/api/run.py

Use optimized tag filter query when order key is `flow_id` and/or `ts_epoch`. Otherwise use the non-performant query that supports computed columns from joins.

Optimized tag filters for flow_id, ts_epoch order

---

services/ui_backend_service/api/heartbeat_monitor.py

- fixes regression bug with heartbeat monitor interval being too narrow compared to modified heartbeat_threshold from the db queries.
- ties the heartbeat interval to the threshold used in queries.

fix issue with heartbeat monitoring interval

---

services/data/models.py
services/data/postgres_async_db.py
services/ui_backend_service/api/step.py
services/ui_backend_service/doc.py
services/ui_backend_service/tests/integration_tests/steps_test.py

- adds logic to determine a current duration for a step
- includes integration test for step duration

Add duration to steps

---

services/ui_backend_service/data/refiner/refinery.py

- handles occasional 'None' return from cache in Refinery classes.

Handle cache None return in refinery

---

services/ui_backend_service/data/db/tables/task.py

- update task table class comment on table joins. Original comment got lost in the custom DB adapter merge

docs: update comments

---

services/ui_backend_service/api/features.py
services/ui_backend_service/api/heartbeat_monitor.py
services/ui_backend_service/api/notify.py
services/ui_backend_service/api/ws.py
services/ui_backend_service/data/cache/generate_dag_action.py
services/ui_backend_service/data/cache/get_artifacts_action.py
services/ui_backend_service/data/cache/search_artifacts_action.py
services/ui_backend_service/data/cache/store.py
services/ui_backend_service/data/db/models/base_row.py
services/ui_backend_service/data/db/postgres_async_db.py
services/ui_backend_service/data/db/tables/base.py
services/ui_backend_service/data/refiner/parameter_refiner.py
services/ui_backend_service/data/refiner/refinery.py
services/ui_backend_service/data/refiner/task_refiner.py
services/ui_backend_service/features.py
services/ui_backend_service/ui_server.py

- updates ui_backend docstrings for multiple functions and classes
- adds some type hints for functions.
- sort imports

docs: update documentation

---

services/ui_backend_service/api/autocomplete.py
services/ui_backend_service/doc.py
services/ui_backend_service/tests/integration_tests/utils.py

- update swagger documentation for autocomplete routes
- fix some pycodestyle errors
- revert unnecessary change to integration test utils

fix: clean up pycodestyle errors, update api docs, revert unnecessary test util changes

---

services/ui_backend_service/api/dag.py
services/ui_backend_service/data/cache/generate_dag_action.py
services/ui_backend_service/doc.py

Example DAG Node JSON object with Docstring:
```json
{
"process_foreach": {
"type": "linear",
"box_next": false,
"box_ends": null,
"next": ["join_foreach"],
"doc": "Multiline\n\ndocstring"
}
}
```

feat[dag]: Include Docstring for each DAG node

---

Dockerfile
MANIFEST.in
requirements.txt
services/data/db_utils.py
services/data/postgres_async_db.py
services/data/service_configs.py
services/metadata_service/api/admin.py
services/metadata_service/api/artifact.py
services/metadata_service/api/flow.py
services/metadata_service/api/metadata.py
services/metadata_service/api/run.py
services/metadata_service/api/step.py
services/metadata_service/api/task.py
services/metadata_service/api/utils.py
services/metadata_service/requirements.txt
services/metadata_service/tests/unit_tests/api_util_test.py
services/migration_service/api/admin.py
services/migration_service/api/utils.py
services/migration_service/get_virtual_env.py
services/migration_service/requirements.txt
services/migration_service/run_script.py
services/ui_backend_service/api/artifact.py
services/ui_backend_service/api/notify.py
services/ui_backend_service/api/ws.py
services/ui_backend_service/tests/integration_tests/admin_test.py
services/ui_backend_service/tests/integration_tests/utils.py
services/utils/__init__.py
setup.py
wait-for-postgres.sh

Merge `master` branch back to `ui` after `2.0.5` release candidate.

Merge master to ui branch

---

services/ui_backend_service/.gitignore
services/ui_backend_service/api/admin.py
services/ui_backend_service/api/autocomplete.py
services/ui_backend_service/api/utils.py
services/ui_backend_service/data/db/tables/run.py
services/ui_backend_service/data/db/tables/step.py
services/ui_backend_service/data/db/tables/task.py

- clean up unused imports and constants
- clean up ui service gitignore
- move utility function to utils
- change some docstrings that were meant as comments.

chore: UI service cleanup

---

services/ui_backend_service/api/autocomplete.py
services/ui_backend_service/data/db/tables/artifact.py
services/ui_backend_service/doc.py
services/ui_backend_service/tests/integration_tests/autocomplete_test.py

- adds autocomplete support for artifact names
- some clean up for the autocomplete controller

feat: add autocomplete route for artifact names.

---

services/ui_backend_service/tests/integration_tests/ws_test.py

- fixes web socket subscription condition checks integration test coverage.
- also fixes common ws test pattern that leads to false-positives.

fix: integration test coverage for web socket subscription conditions 

---

services/ui_backend_service/api/artifactsearch.py
services/ui_backend_service/data/cache/get_artifacts_action.py
services/ui_backend_service/data/cache/search_artifacts_action.py
services/ui_backend_service/data/cache/utils.py
services/ui_backend_service/tests/unit_tests/cache_utils_test.py

- improves error messaging for artifact search, now catching server errors and broadcasting them over the websocket as well.
- some refactoring on cache actions. introduced message formatter helpers for consistency

feat: better artifact search error handling

---

Dockerfile.ui_service
services/ui_backend_service/data/cache/client/__init__.py
services/ui_backend_service/data/cache/client/cache_action.py
services/ui_backend_service/data/cache/client/cache_async_client.py
services/ui_backend_service/data/cache/client/cache_client.py
services/ui_backend_service/data/cache/client/cache_server.py
services/ui_backend_service/data/cache/client/cache_store.py
services/ui_backend_service/data/cache/client/cache_sync_client.py
services/ui_backend_service/data/cache/client/cache_worker.py
services/ui_backend_service/data/cache/generate_dag_action.py
services/ui_backend_service/data/cache/get_artifacts_action.py
services/ui_backend_service/data/cache/search_artifacts_action.py
services/ui_backend_service/data/cache/store.py
services/ui_backend_service/requirements.txt
tox.ini

- integrates https://github.com/Netflix/metaflow/pull/316 as part of the ui backend service due to it not being merged yet
- fix some conflicting dependencies

feat: integrate cache server fork to ui backend

---

services/ui_backend_service/api/log.py

Adds support for downloading task log files without pagination. Also refactors MFLOG path finding logic to separate function for reusability

feat: add support for downloading logs

---

services/ui_backend_service/api/notify.py
services/ui_backend_service/data/cache/store.py
services/ui_backend_service/tests/integration_tests/notify_test.py

feat[dag]: Preload DAG

---

services/ui_backend_service/data/cache/client/cache_async_client.py
services/ui_backend_service/data/cache/store.py

Cache worker drain timeout error indicates unrecoverable critical issue, essentially the cache functionality remains broken after the first `asyncio.TimeoutError` (drain lock) occures.
`CacheAsyncClient` can now request restart for itself and `CacheStore` will monitor these requests periodically (every 5s) so that normal operation can be resumed.

fix[cache]: Cache worker recovery by restart.

---

services/ui_backend_service/plugins/plugin.py
services/ui_backend_service/tests/integration_tests/plugins_test.py

fixes file path issues with multiple plugins in one cloned repository. Changes so that repository is only cloned once and reused for all contained plugin folders.

fix: plugin loading issues

---

services/ui_backend_service/api/notify.py
services/ui_backend_service/api/ws.py
services/ui_backend_service/tests/integration_tests/notify_test.py

- re-enables websocket resource subscriptions for metadata and artifacts
- broadcasts artifacts as refined resources to better serve the UI

fix: metadata and artifact ws subscription issues

---

services/ui_backend_service/data/db/tables/task.py
services/ui_backend_service/tests/integration_tests/tasks_test.py

- adds a new 'pending' status to tasks that have not yet begun executing (do not have any metadata/artifacts associated with them)

feat: add pending status to tasks

---

services/data/postgres_async_db.py

Introduced in https://github.com/Netflix/metaflow-service/pull/222 but then rolled back https://github.com/Netflix/metaflow-service/pull/235/. Added a more detailed explanation too

fix retrieving the latest artifact

---

Dockerfile.ui_service
services/ui_backend_service/data/cache/get_cards_action.py
services/ui_backend_service/requirements.txt

- setting mf version to card compatible

Fixing card import bug

---

.github/workflows/test.yml

Run GH tests on PRs from forks too

---

README.md

Add instructions on how to execute flows against a local metadata service.

docs: add local metadata service usage instructions to readme.

---

Dockerfile
Dockerfile.ui_service
services/ui_backend_service/requirements.txt

Pre-release fixes.

---

Dockerfile.ui_service

Fix https://github.com/Netflix/metaflow-service/issues/311 by upgrading pip in `Dockerfile.ui_service`

Upgrade pip in `Dockerfile.ui_service` to version 22.0.4

---

docker-compose.development.yml
run_goose.py

Run migrations in docker compose using the new script

---

.github/workflows/codeql.yml

feature: add CodeQL

---

.github/workflows/dockerimage.yml
.github/workflows/test.yml

- pin workflow steps to hashes

feature: pin workflow steps

---

services/ui_backend_service/requirements.txt

Update Metaflow client library version to avoid side-effects during service release build

fix: S3 access for MinIO resources

---

services/ui_backend_service/api/utils.py

Use f-strings for log message

---

services/metadata_service/server.py

Similar functionality in MFGUI backend already exists and uses same var. This allows one to modify HTTP path for metadata service endpoint.

support PATH_PREFIX var in metadata service

---

run_goose.py
services/utils/__init__.py

Fixes sslmode query parameter typo in goose migrations script.

fix: change ssl_mode to sslmode

---

setup.py

2.4.10 was unfortunately taken but not merged to master. skipping to next version

bump version to 2.4.11

---

services/ui_backend_service/data/cache/get_log_file_action.py
services/ui_backend_service/data/cache/search_artifacts_action.py
services/utils/__init__.py
tox.ini

fix: linting issues

---

services/ui_backend_service/data/cache/get_log_file_action.py

fix fetch logs returning none in certain cases, leading to log read failures

fix: log paths failure

---

services/ui_backend_service/data/cache/get_log_file_action.py
services/ui_backend_service/tests/unit_tests/get_log_file_action_test.py

fixes existing issue with log sorting the streamed output

fix: correctly sort log lines based on utc_tstamp
